# Generated by Django 4.2.5 on 2023-10-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Curso')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('imagen', models.ImageField(blank=True, upload_to='Tienda')),
                ('creditos', models.IntegerField(verbose_name='Creditos')),
                ('cupo', models.IntegerField(verbose_name='Cupo')),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
    ]
