# Generated by Django 4.2.5 on 2023-10-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion', '0002_cursos_created_cursos_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cursos',
            new_name='curso',
        ),
    ]
