# Generated by Django 4.2.5 on 2023-10-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_estudiantes_first_name_and_more'),
        ('Asignacion', '0005_notas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notas',
            new_name='Nota',
        ),
    ]
