# Generated by Django 4.2.5 on 2023-10-24 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Asignacion', '0006_rename_notas_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='docentes_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_docentes', to='auth.group'),
        ),
    ]
