# Generated by Django 4.2.5 on 2023-10-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion', '0008_remove_curso_docentes_group_docente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
