# Generated by Django 4.2.5 on 2023-10-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion', '0010_alter_curso_options_alter_curso_creditos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='creditos',
            field=models.IntegerField(verbose_name='Creditos'),
        ),
    ]
