# Generated by Django 4.2.5 on 2023-10-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Nombre y Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('contact', models.IntegerField(choices=[[0, 'Informacion de ingreso'], [1, 'No sirve el portal'], [2, 'Seguimiento de un tramite']], verbose_name='Tipo de contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envio')),
            ],
        ),
    ]
