# Generated by Django 4.2.5 on 2023-10-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.IntegerField(choices=[[0, 'Informacion de ingreso'], [1, 'Bloqueo de Usuario'], [2, 'Seguimiento de un tramite para Docente'], [3, 'No sirve el portal']], verbose_name='Tipo de contacto'),
        ),
    ]
