# Generated by Django 4.2.5 on 2023-10-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiantes',
        ),
    ]
