# Generated by Django 4.2.5 on 2023-10-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='username',
            field=models.CharField(default='user', max_length=150),
        ),
    ]
