# Generated by Django 4.2.5 on 2023-10-24 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0004_alter_estudiantes_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='first_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_first_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='last_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_last_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
