# Generated by Django 4.2.5 on 2023-10-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_estudiantes_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='first_name',
            field=models.CharField(default='Nombres', max_length=150),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='last_name',
            field=models.CharField(default='Apellidos', max_length=150),
        ),
    ]
