# Generated by Django 4.2.5 on 2023-10-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
